appName: backend
replicaCount: 3

image:
  repository: nginx # Imagen dummy por ahora
  tag: alpine

containerPort: 80

service:
  type: ClusterIP
  port: 80


ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  hosts:
    - host: "34.176.243.245"
      paths:
        - path: /
          pathType: Prefix # Regla que permite buscar coincidencias basadas en el inicio de la ruta.
