appName: backend
replicaCount: 3

image:
  repository: dressy/mi-backend
  tag: aa5407f7fb931f606bbf7a24f41e697be5a2937f

containerPort: 5000

service:
  type: ClusterIP # Servicio que crea una IP interna virtual. Solo es accesible dentro del cluster.
  port: 80
  targetPort: 5000

config:
  db_host: "db-service.db.svc.cluster.local"
  db_port: "5432"
  db_user: "postgres"
  db_secret_name: "db-pass-secret"


ingress:
  enabled: true
  className: traefik # Ingress controler nativo de k3s
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /api
          pathType: Prefix # Regla que permite buscar coincidencias basadas en el inicio de la ruta.

