appName: backend
replicaCount: 3

image:
  repository: nginx # Imagen dummy por ahora
  tag: alpine

containerPort: 80

service:
  type: ClusterIP
  port: 80


ingress:
  enabled: true
  className: traefik # Ingress controler nativo de k3s
  annotations: 
    #Esto le dice a Traefik que elimine el prefijo /api al pasar el tráfico
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-{{ .Values.appName }}-strip-prefix@traefik"
  hosts:
    - host: ""
      paths:
        - path: /api
          pathType: Prefix # Regla que permite buscar coincidencias basadas en el inicio de la ruta.
