config:
  datasourceSecret:
    # Nombre del Secret que contiene la contraseña de la base de datos
    name: "db-pass-secret" 
    # La llave dentro del secret donde está la contraseña
    key: "password"
    
    user: "postgres"
    host: "db-service.db.svc.cluster.local" # El nombre del service de la base de datos, seguido del namespace y el dominio del cluster.
    port: 5432
    database: "postgres"
    sslmode: "disable"

serviceMonitor:
  enabled: true
  labels:
    release: prometheus
  interval: 30s