apiVersion: traefik.containo.us/v1alpha1 # Version distinta porque no es nativa de Kubernetes, sino una CRD (Custom Resource Definition) de Traefik
kind: Middleware
metadata:
  name: {{ .Values.appName }}-strip-prefix
spec:
  stripPrefix:
    prefixes:
      - /api