{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{.Values.appName }}-monitor
  namespace: {{.Values.metrics.serviceMonitor.namespace}}
  labels:
    release: {{.Values.metrics.serviceMonitor.selector}}
spec:
  selector:
    matchLabels:
      app: {{.Values.appName }}
  namespaceSelector:
    matchNames:
      - {{.Values.metrics.serviceMonitor.namespace}}
  endpoints:
  - port: {{.Values.metrics.serviceMonitor.port}}
    interval: {{.Values.metrics.serviceMonitor.interval}}
    path: {{.Values.metrics.serviceMonitor.path}} 
{{- end }}