appName: frontend
replicaCount: 3

image:
  repository: dressy/mi-frontend
  tag: 799981824c6e663d4bd5474cada3e26ec822849c

containerPort: 80

metrics:
  enabled: true
  sidecar:
    repository: nginx/nginx-prometheus-exporter
    tag: 1.1.0
    port: 9113
  # Esta es la ruta que configuramos en tu nginx.conf
  scrapeUri: "http://localhost:80/nginx_status"

service:
  type: ClusterIP # Servicio que crea una IP interna virtual. Solo es accesible dentro del cluster.
  port: 80
  targetPort: 80


ingress:
  enabled: true
  className: traefik # Ingress controler nativo de k3s
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix # Regla que permite buscar coincidencias basadas en el inicio de la ruta.

