appName: frontend
replicaCount: 2

image:
  repository: dressy/mi-frontend
  tag: 8489b249c85206dd088d35b60c07c9542bceca53

containerPort: 80

metrics:
  enabled: true
  name: nginx-exporter
  sidecar:
    repository: nginx/nginx-prometheus-exporter
    tag: "1.1.0"
    port: 9113
  # La ruta de nginx.conf
  scrapeUri: "http://localhost:80/nginx_status"

service:
  type: ClusterIP # Servicio que crea una IP interna virtual. Solo es accesible dentro del cluster.
  port: 80
  targetPort: 80


ingress:
  enabled: true
  className: traefik # Ingress controler nativo de k3s
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix # Regla que permite buscar coincidencias basadas en el inicio de la ruta.

