appName: frontend
replicaCount: 2

image:
  repository: dressy/mi-frontend
  tag: bc6aba69ece458d2e423f310e69b148cd20a1619

containerPort: 80

metrics:
  enabled: true
  name: nginx-exporter
  sidecar:
    repository: nginx/nginx-prometheus-exporter
    tag: "1.1.0"
    port: 9113
  # La ruta de nginx.conf
  scrapeUri: "http://localhost:80/nginx_status"
  serviceMonitor:
    namespace: monitoring 
    selector: prometheus
    interval: 15s
    port: metrics

service:
  type: ClusterIP # Servicio que crea una IP interna virtual. Solo es accesible dentro del cluster
  port: 80
  targetPort: 80


ingress:
  enabled: true
  className: traefik # Ingress controler nativo de k3s
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix # Regla que permite buscar coincidencias basadas en el inicio de la ruta.

