{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  namespace: monitoring # El ns donde está Prometheus
  labels:
    release: prometheus # Debe coincidir con el nombre que se le asignó al instalador cuando se ejecutó el comando de Helm
spec:
  selector:
    matchLabels:
      app: frontend # Debe hacer match con el label de frontend
  namespaceSelector:
    matchNames:
      - frontend # Debe hacer match con el ns de frontend
  endpoints:
  - port: metrics # El nombre del puerto en el service
    interval: 15s # Intervalo de recolección
{{- end }}